version: '3'
services:
  scanserver:
    build: .
    privileged: true
    restart: always
    volumes: 
      - /dev/bus/usb:/dev/bus/usb
      - files:/scan

    tmpfs:
      - /tmp
    network_mode: none

  ftp:
    build: ftp
    restart: always
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - USERS=scan|scan||10000

    volumes:
      - files:/ftp/scan

    #network_mode: host

volumes:
  files:
