version: '3'
services:
  scanserver:
    build: .
    privileged: true
    volumes: 
      - /dev/bus/usb:/dev/bus/usb
      - files:/scan

    tmpfs:
      - /tmp

  ftp:
    image: delfer/alpine-ftp-server
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - USERS=scan|scan||10000

    volumes:
      - files:/ftp/scan


  # web:
  #   image: nginx
  #   ports:
  #   - "8080:80"
  #   environment:
  #   - NGINX_HOST=foobar.com
  #   - NGINX_PORT=80

volumes:
  files: