- hosts: scanner
  tasks:
  - name: Set hostname
    hostname:
      name: scanner

  - name: Set correct timezone
    timezone:
      name: Europe/Vienna

  - name: Add the scan user
    user:
      name: scan
      password: $1$agjuh8aa$4JEAdl67FDjFbIL4N1Ilu.
      group: scanner

  
  - name: Copy network config
    copy:
      src: files/eth0.network
      dest: /etc/systemd/network/eth0.network
      owner: root
      group: root
      mode: u=rw,g=r,o=r
    register: network

  - name: Restart systemd-networkd
    service:
      name: systemd-networkd
      state: restarted
    when: network.changed

  - name: Install requirements for makepkg
    pacman:
      name: "{{ item }}"
      state: present
    loop:
      - base-devel
      - git

  - name: Add the aurbuilder user
    user:
      name: aurbuilder
      group: wheel

  - name: Edit sudo config for aurbuilder
    lineinfile:
      path: /etc/sudoers.d/11-install-aurbuilder
      line: 'aurbuilder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      validate: 'visudo -cf %s'

  - name: Install AUR packages
    aur:
      name: "{{ item }}"
      use: makepkg
      skip_installed: true
    become: yes
    become_user: aurbuilder
    loop:
      - scanbd
      - raspi-config

  - name: Copy scanbd service file
    copy:
      src: files/myscanbd.service
      dest: /etc/systemd/system/myscanbd.service
      owner: root
      group: root
      mode: u=rw,g=r,o=r
    register: reloadsystemd

  - name: Reload systemd services
    command: systemctl daemon-reload
    when: reloadsystemd.changed

  - name: Enable and start custom scanbd service
    service:
      name: myscanbd
      state: started
      enabled: yes
    